volumes:
  mariadb:
  opensearch-data1:
  opensearch-data2:
  ssl-certs: #volume for SSL, so multiple container can use it

networks:
  magento:
    driver: bridge

services:
  mariadb:
    image: mariadb:11.4.5
    networks:
      - magento
    env_file:
      - docker/env/mariadb.env
    volumes:
      - type: bind
        source: ./docker/images/mariadb/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./docker/images/mariadb/init.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: mariadb
        target: /var/lib/mysql

  nginx:
    build:
      context: ./docker/images/nginx
      args:
        app_user_id: ${APP_USER_ID}
        app_group_id: ${APP_GROUP_ID}
    depends_on:
      - php-fpm
      - mariadb
    ports:
      - 80:80
      - 443:443
    networks:
      - magento
    volumes:
      - type: bind
        source: ./docker/images/nginx/log
        target: /var/log/nginx
      - type: bind
        source: ./build
        target: /var/www/html
      - type: volume
        source: ssl-certs
        target: /etc/nginx/certs

  php-fpm:
    build:
      context: ./docker/images/php
      args:
        app_user_id: ${APP_USER_ID}
        app_group_id: ${APP_GROUP_ID}
        user_name: ${USER_NAME}
        password: ${PASSWORD}
        app_version: ${VERSION}
    networks:
      - magento
    volumes:
      - ./build:/var/www/html
    ports:
      - 9000:9000
    
  opensearch-primary:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-primary
    ulimits:
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    env_file:
      - docker/env/opensearch-primary.env
    volumes:
      - type: bind
        source: ./docker/images/opensearch/config/jvm.options
        target: /config/jvm.options
      - type: volume
        source: opensearch-data1
        target: /usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - magento

  opensearch-secondary:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-secondary
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - docker/env/opensearch-secondary.env
    volumes:
      - type: bind
        source: ./docker/images/opensearch/config/jvm.options
        target: /config/jvm.options
      - type: volume
        source: opensearch-data2
        target: /usr/share/opensearch/data
    networks:
      - magento
