services:

  # before enable it, make sure you have package.json in root directory
  node:
    container_name: ${NODE_CONTAINER}
    build:
      context: ./docker/images/node
      args:
        app_user_id: ${APP_USER_ID}
        app_group_id: ${APP_GROUP_ID}
    depends_on:
      - php-fpm
    ports:
      - "${HOST_MACHINE_NODE_PORT}:${CONTAINER_NODE_PORT}"
    expose:
      - ${CONTAINER_NODE_PORT}
    networks:
      - magento
    volumes:
      - ./build:/var/www/html
    environment:
      - NODE_ENV=development
