volumes:
  mariadb:
  opensearch-data1:
  opensearch-data2:
  ssl-certificate:
  #volume for SSL, so multiple container can use it

networks:
  magento:
    driver: bridge

services:
  mariadb:
    container_name: ${MARIADB_CONTAINER}
    image: mariadb:11.4.5
    networks:
      - magento
    env_file:
      - docker/env/mariadb.env
    volumes:
      - type: bind
        source: ./docker/images/mariadb/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./docker/images/mariadb/init.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: mariadb
        target: /var/lib/mysql

  php-fpm:
    container_name: ${PHP_FPM_CONTAINER}
    build:
      context: ./docker/images/php
      args:
        app_user_id: ${APP_USER_ID}
        app_group_id: ${APP_GROUP_ID}
    networks:
      - magento
    volumes:
      - ./build:/var/www/html
    ports:
      - ${HOST_MACHINE_PHP_FPM_PORT}:${CONTAINER_PHP_FPM_PORT}
    expose:
      - ${CONTAINER_PHP_FPM_PORT}

  nginx:
    container_name: ${NGINX_CONTAINER}
    build:
      context: ./docker/images/nginx
      args:
        app_user_id: ${APP_USER_ID}
        app_group_id: ${APP_GROUP_ID}
    depends_on:
      - php-fpm
      - mariadb
    ports:
      - ${HOST_MACHINE_NGINX_HTTP_PORT}:${CONTAINER_NGINX_HTTP_PORT}
      - ${HOST_MACHINE_NGINX_HTTPS_PORT}:${CONTAINER_NGINX_HTTPS_PORT}
    expose:
      - ${CONTAINER_NGINX_HTTP_PORT}
      - ${CONTAINER_NGINX_HTTPS_PORT}
    networks:
      - magento
    volumes:
      - type: bind
        source: ./docker/images/nginx/log
        target: /var/log/nginx
      - type: bind
        source: ./build
        target: /var/www/html
      - type: volume
        source: ssl-certificate
        target: /etc/nginx/certs

  opensearch-primary:
    image: opensearchproject/opensearch:2.19.1
    container_name: ${PRIMARY_OPENSEARCH_CONTAINER}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - docker/env/opensearch-primary.env
    volumes:
      - type: bind
        source: ./docker/images/opensearch/config/jvm.options
        target: /config/jvm.options
      - type: volume
        source: opensearch-data1
        target: /usr/share/opensearch/data
    ports:
      - ${HOST_MACHINE_PRIMARY_OPENSEARCH_PORT}:${CONTAINER_PRIMARY_OPENSEARCH_PORT}
      - ${HOST_MACHINE_SECONDARY_OPENSEARCH_PORT}:${CONTAINER_SECONDARY_OPENSEARCH_PORT}
    networks:
      - magento

  opensearch-secondary:
    image: opensearchproject/opensearch:2.19.1
    container_name: ${SECONDARY_OPENSEARCH_CONTAINER} 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - docker/env/opensearch-secondary.env
    volumes:
      - type: bind
        source: ./docker/images/opensearch/config/jvm.options
        target: /config/jvm.options
      - type: volume
        source: opensearch-data2
        target: /usr/share/opensearch/data
    networks:
      - magento
