memory_limit = -1
max_execution_time = 1800
zlib.output_compression = On
date.timezone = UTC
upload_max_filesize = 100M
post_max_size = 100M
realpath_cache_size=12M
realpath_cache_ttl=86400
# xdebug
[xdebug]
zend_extension=xdebug.so
xdebug.mode=off
xdebug.max_nesting_level=1000
xdebug.start_with_request=no
xdebug.discover_client_host=false
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.log=/var/log/xdebug/xdebug.log
xdebug.output_dir=/var/log/xdebug